### ISSUE TITLE
./monitor.sh build

### ISSUE THREAD

**Issue by jordipainan** [alastria/alastria-node#130]
Error haciendo build del monitor para los nodos.

![errormonitor](https://user-images.githubusercontent.com/17238033/37097790-9e12a144-221c-11e8-9ef5-1e65756d5a99.png)

**Comment by marcossanlab** [comment]
Hola Jordi,

Necesitamos edites el fichero `~/alastria/workspace/src/github.com/alastria/monitor/glide.yaml` y lo cambies por:

```
package: github.com/alastria/monitor
import:
- package: github.com/ethereum/go-ethereum
  subpackages:
  - accounts/abi
  - accounts/abi/bind
  - common
  - core/types
  - ethclient
  - rpc
- package: github.com/robfig/cron
- package: github.com/hashicorp/go-getter
- package: github.com/ory-am/hydra
  version: ~0.7.7
  subpackages:
  - sdk
- package: github.com/astaxie/beego
  version: ~v1.9.2
# To clean glide installations when there are errors:
# $HOME/.glide/cache/
```
